#!/bin/bash
set -e

# Build site
zola build

cd public

# Remove public/.git dir if it exists
rm -rf .git

# Initialize public/ as an empty git repo
git init

# Commit all the generated files as the initial commit
git add -A
git commit -m "Add files generated by zola"

# Push the commit to the gh-pages branch
git push -f git@github.com:jplatte/blog.turbo.fish master:gh-pages
